version: "3"

services:
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  web:
    build: .
    command: gunicorn socialbot/socialbot.wsgi.application --bind 0.0.0.0:8000 --certfile cognition-srv2_ouc_ac_cy.pem --keyfile cogition-srv2a.key
    volumes:
      - .:/code
      - .:/root/.ssh:rw
    ports:
      - "443:8000"
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - APP_ID=sa0RgS4xDL
      - APP_SECRET=0F5yOXGyDodqP9f1Cznr
      - WENET_AUTHENTICATION_COMPLETE=https://wenet.u-hopper.com/dev/hub/frontend/oauth/login?client_id=sa0RgS4xDL
      - WENET_TOKEN_GENERATOR=https://wenet.u-hopper.com/dev/api/oauth2/token
      - WENET_WEBSITE=https://wenet.u-hopper.com/dev/hub/frontend
      - WENET_SERVICES=https://wenet.u-hopper.com/dev/api/service
      - TELEGRAM_URI=https://t.me/sociaLabGRCYTRCYBot?start=
      - BOT_TOKEN=5190722737:AAHrk9MCT01h646wPP9G5M2qjOYm3fiRYtw
    depends_on:
      - db
  bot:
    build: .
    command: python bot/src/main.py
    environment:
      - SERVER=https://cognition-srv2.ouc.ac.cy:443/wenet
      - APP_ID=sa0RgS4xDL
      - WENET_AUTHENTICATION=https://wenet.u-hopper.com/dev/hub/frontend/oauth/login?client_id=sa0RgS4xDL
      - WENET_SIGN_UP=https://wenet.u-hopper.com/dev/hub/frontend/user/signup
      - WENET_TOKEN_GENERATOR=https://wenet.u-hopper.com/dev/api/oauth2/token
      - WENET_WEBSITE=https://wenet.u-hopper.com/dev/hub/frontend
      - BOT_TOKEN=5190722737:AAHrk9MCT01h646wPP9G5M2qjOYm3fiRYtw
    depends_on:
      - web
