version: "3"

services:
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  web:
    build: .
    command: python socialbot/manage.py runserver_plus 0.0.0.0:8000 --cert-file cognition-srv2_ouc_ac_cy.pem --key-file cogition-srv2a.key
    volumes:
      - .:/code
      - .:/root/.ssh:rw
    ports:
      - "443:8000"
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    depends_on:
      - db
  bot:
    build: .
    command: python bot/source/main.py
    environment:
      - SERVER = 'https://localhost/wenet'
      - APP_ID = 'mH7Tbcd0W5'
      - WENET_AUTHENTICATION = 'https://wenet.u-hopper.com/dev/hub/frontend/oauth/login?client_id={mH7Tbcd0W5}'
      - WENET_TOKEN_GENERATOR = 'https://wenet.u-hopper.com/dev/api/oauth2/token'
    depends_on:
      - web
