# Generated by Django 3.2.12 on 2022-03-21 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wenet_webhooks', '0002_auto_20220321_0913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.PositiveBigIntegerField(primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
