# Generated by Django 3.2.12 on 2022-03-22 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wenet_webhooks', '0003_alter_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='telegram_id',
            field=models.PositiveBigIntegerField(default=0, unique=True, verbose_name='telegram ID'),
        ),
    ]
