# Generated by Django 3.2.12 on 2022-03-28 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wenet_webhooks', '0004_user_telegram_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='solved',
            field=models.BooleanField(default=False),
        ),
    ]
