# Generated by Django 3.2.13 on 2022-04-28 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wenet_webhooks', '0005_question_solved'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='task_id',
            field=models.CharField(default='', max_length=128, unique=True),
        ),
    ]
