# Generated by Django 3.2.13 on 2022-05-03 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wenet_webhooks', '0006_question_task_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='answer_text',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='question_text',
            new_name='content',
        ),
    ]
