# Generated by Django 3.2.13 on 2022-05-04 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wenet_webhooks', '0007_auto_20220503_0818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='language',
            field=models.CharField(max_length=5),
        ),
    ]
